language: csharp
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
solution: Unosquare.Labs.SshDeploy.sln
mono: none
dotnet: 2.1.300
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode9.1
install:
  - dotnet restore
script:
- dotnet build
- dotnet pack
- dotnet tool install -g dotnet-sshdeploy --add-source ./
